### ISSUE TITLE
Comman 'bsdtar' failed with exit status 1

### ISSUE THREAD

**Issue by mattisengstedt** [bswebdk/x2pinn#2]
I flashed the image to a usb stick and used that instead, that got me a bit further but it failed when compressing the tar to xz instead.

The first partition succeeds but the second one fails during tarball creation.

'Command 'bsdtar' failed with exit status 1'

When I instead use -debugging i get past that step with log message "bsdtar: ./urs..../emscripten: Coudl´t visit directory: Unknown error -1"

This generates the files but fails to install. Pinn log shows that i can´t enter fstab, no such file or directory.

**Comment by mattisengstedt** [comment]
Sorry for posting all these issues, really want to make this work. I have dreams.

**Comment by bswebdk** [comment]
To me it looks like there may be open sockets in the file system, which will cause bsdtar to fail. Have you tried to apply the "nosock" and/or "getfacl" tokens to the partition settings for the second partition?

You may also need to create a custom "partition_setup.sh" script in order to allow PINN to setup the partitions correctly.

**Comment by bswebdk** [comment]
I've tried to download dosbian and look into it. I assume that you have an image file named "extracted.img" in a directory, and if you run the command: `sudo losetup -o 541065216 --sizelimit 5602541568 -b 512 -f extracted.img`

You will setup a loop device for the second partition, to get the name of the loop device, run: `losetup -j extracted.img`

It will output something like "/dev/loopX ...", the next command assumes "/dev/loop123". Now you try to run: `sudo fsck /dev/loop123`

And you will see that either the superblock or the partition table is corrupt. If you select "Y" at the prompt, you will get information about a corrupted directory. You may have luck salvaging the directory, but the dosbian image is provided as corrupt.

To release the loop device, run: `sudo losetup -d /dev/loop123`

There is really nothing I can do about this, you should try to contact the provider of dosbian in order to get this fixed. Maybe [he|she] does not know there is a problem with the system image.

**Comment by mattisengstedt** [comment]
Thank you for going above and beyond to look into it yourself, I´ll make the provider aware of the issue and hope that he´ll take the time to fix it. Since it works when you only flash the image to an SD och USB stick I doubt it however.
